---

- name: Check if Oh My Zsh is installed
  stat: 
    path: ~/.oh-my-zsh 
  register: oh_my_zsh
  become: false

- name: Install Oh My Zsh if not installed already
  shell: sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: oh_my_zsh.stat.exists == false
  become: false

- name: Fix path issue 
  lineinfile:
    path: /etc/zsh/zprofile
    state: present
    regexp: emulate sh -c 'source /etc/profile'
    line: emulate sh -c 'source /etc/profile'
    
- name: Get current user name
  shell: echo $USER
  register: current_user
  become: false

- name: Set ZSH as the default shell
  command: /usr/sbin/usermod --shell /usr/bin/zsh {{ current_user.stdout_lines[0] }}

- name: Set ZSH theme
  lineinfile:
    path: ~/.zshrc
    regexp: '^ZSH_THEME=' 
    line: ZSH_THEME="fino`"
  become: false
  
- name: Set ZSH plugins
  lineinfile:
    path: ~/.zshrc
    regexp: '^plugins=' 
    line: plugins=(command-not-found colored-man-pages)
  become: false
