---

- name: Add .vimrc
  copy:
    src: .vimrc
    dest: ~/
    force: false
  become: false

- name: Add .gvimrc
  copy:
    src: .gvimrc
    dest: ~/
    force: false
  become: false

- name: Add .vim folder
  copy:
    src: .vim
    dest: ~/
    force: false
  become: false

- name: Get Vundle
  git:
    repo: git://github.com/gmarik/vundle.git
    dest: ~/.vim/bundle/vundle
    clone: true
    update: true
    accept_hostkey: true
    force: false
  become: false
  
- name: Install plugins
  command: vim +BundleInstall! +quitall 
  become: false