---

- name: Brutally destroy existin gitconfig
  ansible.builtin.file:
    path: ~/.gitconfig
    state: absent
  become: false

- name: Basic Git settings
  copy:
    src: .gitconfig
    dest: ~/
  become: false